package com.goryachok.forecastapp.base

const val SECOND_MS = 1000L
const val MINUTE_MS = 60 * SECOND_MS
const val HOUR_MS = 60 * MINUTE_MS

const val PREF_NAME = "WEATHER_APPLICATION_PREFERENCES"
const val WEATHER_PREF = "LOCAL_WEATHER_PREFERENCES"
const val FORECAST_PREF = "LOCAL_FORECAST_PREFERENCES"